# Generated by Django 6.0.5 on 2026-05-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_remove_student_lecture_enrollment_student_lecture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='LectureStudent',
        ),
        migrations.RenameField(
            model_name='lecturestudent',
            old_name='date_enrolled',
            new_name='enrolled_at',
        ),
    ]
