# Generated by Django 6.0.4 on 2026-04-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Guest',
        ),
    ]
